const fs = require('fs');
const content = [
  '',
  'const KEYS = [',
  '];',
  '',
  'interface KeyboardProps {',
  '  guesses: Set<string>;',
  '  word: string;',
  '  onGuess: (letter: string) => void;',
  '  disabled?: boolean;',
  '}',
  '',
  'export const Keyboard: React.FC<KeyboardProps> = ({ guesses, word, onGuess, disabled }) => {',
  '  useEffect(() => {',
  '    const handleKeyDown = (e: KeyboardEvent) => {',
  '      if (disabled) return;',
  '      const key = e.key.toUpperCase();',
  '      if (/^[A-Z]$/.test(key)) {',
  '        onGuess(key);',
  '      }',
  '    };',
  '  }, [onGuess, disabled]);',
  '',
  '  return (',
  '      {KEYS.map((row, i) => (',
  '          {row.map(key => {',
  '            const isGuessed = guesses.has(key);',
  '            const isCorrect = isGuessed && word.includes(key);',
  '            const isWrong = isGuessed && !word.includes(key);',
  '',
  '            return (',
  '              <button',
  '                key={key}',
  '                disabled={isGuessed || disabled}',
  '                onClick={() => onGuess(key)}',
  '                className={twMerge(',
  '                  clsx(',
  '                  )',
  '                )}',
  '              >',
  '                {key}',
  '              </button>',
  '            );',
  '          })}',
  '        </div>',
  '      ))}',
  '    </div>',
  '  );',
  '};',
].join('\\n');
fs.writeFileSync('src/components/game/Keyboard.tsx', content);
